kind: Service
apiVersion: v1
metadata:
  name: flask-service
  namespace: flask
spec:
  selector:
    app: flask-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
